filename: texDemo.md
theme: clean
google-font: 
  font1: Eater
  font2:
meta:
  title: Latex Demo
  subtitle: for simple math
  author: doubletony
  email: doubletony@gmail.com
  organization: Pure Michigan
slide:
  navi: true
  ribbon: true
  latex: true